version: '3.8'

services:
  # Auth Service
  auth-service:
    build:
      context: ./microservices/auth-service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-auth
      - DB_PORT=3306
      - DB_DATABASE=wl_school_auth
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql-auth
      - redis
    networks:
      - wl-school-network
    volumes:
      - ./microservices/auth-service:/var/www/html
      - ./storage/logs/auth:/var/www/html/storage/logs

  # Financial Service
  financial-service:
    build:
      context: ./microservices/financial-service
      dockerfile: Dockerfile.dev
    ports:
      - "8002:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-financial
      - DB_PORT=3306
      - DB_DATABASE=wl_school_financial
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql-financial
      - redis
    networks:
      - wl-school-network
    volumes:
      - ./microservices/financial-service:/var/www/html
      - ./storage/logs/financial:/var/www/html/storage/logs
      - /var/www/html/vendor
      - /var/www/html/node_modules

  # Sports Service
  sports-service:
    build:
      context: ./microservices/sports-service
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=sports-db
      - DB_PORT=3306
      - DB_DATABASE=sports_service
      - DB_USERNAME=sports_user
      - DB_PASSWORD=sports_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-jwt-secret-key
      - AUTH_SERVICE_URL=http://auth-service:8000
      - FINANCIAL_SERVICE_URL=http://financial-service:8000
    depends_on:
      - sports-db
      - redis
    networks:
      - wl-school-network
    volumes:
      - ./microservices/sports-service:/var/www/html
      - ./storage/logs/sports:/var/www/html/storage/logs

  # Notification Service
  notification-service:
    build:
      context: ./microservices/notification-service
      dockerfile: Dockerfile
    ports:
      - "8004:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-notifications
      - DB_PORT=3306
      - DB_DATABASE=wl_school_notifications
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis
      - BROADCAST_DRIVER=pusher
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - AUTH_SERVICE_URL=http://auth-service:8000
      - FINANCIAL_SERVICE_URL=http://financial-service:8000
      - SPORTS_SERVICE_URL=http://sports-service:8000
    depends_on:
      - mysql-notifications
      - mysql-calendar
      - redis
    networks:
      - wl-school-network
    volumes:
      - ./microservices/notification-service:/var/www/html
      - ./storage/logs/notifications:/var/www/html/storage/logs

  # Calendar Service
  calendar-service:
    build:
      context: ./microservices/calendar-service
      dockerfile: Dockerfile
    ports:
      - "8005:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-calendar
      - DB_PORT=3306
      - DB_DATABASE=calendar_service
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - AUTH_SERVICE_URL=http://auth-service:8000
      - NOTIFICATION_SERVICE_URL=http://notification-service:8004
      - USER_SERVICE_URL=http://auth-service:8000
    depends_on:
      - mysql-calendar
      - redis
    networks:
      - wl-school-network
    volumes:
      - ./microservices/calendar-service:/var/www/html
      - ./storage/logs/calendar:/var/www/html/storage/logs

  # Medical Service
  medical-service:
    build:
      context: ./microservices/medical-service
      dockerfile: Dockerfile
    ports:
      - "8006:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-medical
      - DB_PORT=3306
      - DB_DATABASE=wl_school_medical
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - AUTH_SERVICE_URL=http://auth-service:8000
      - NOTIFICATION_SERVICE_URL=http://notification-service:8004
      - SPORTS_SERVICE_URL=http://sports-service:8000
      - CALENDAR_SERVICE_URL=http://calendar-service:8005
      - MEDICAL_EXAM_VALIDITY_MONTHS=12
      - INJURY_FOLLOWUP_DAYS=30
      - CERTIFICATE_VALIDITY_DAYS=90
      - MEDICAL_DATA_ENCRYPTION=true
      - GDPR_COMPLIANCE=true
      - DATA_RETENTION_YEARS=7
    depends_on:
      - mysql-medical
      - redis
    networks:
      - wl-school-network
    volumes:
      - ./microservices/medical-service:/var/www/html
      - ./storage/logs/medical:/var/www/html/storage/logs

  # Payroll Service
  payroll-service:
    build:
      context: ./microservices/payroll-service
      dockerfile: Dockerfile.dev
    ports:
      - "8007:9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-payroll
      - DB_PORT=3306
      - DB_DATABASE=wl_school_payroll
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - AUTH_SERVICE_URL=http://auth-service:8000
      - NOTIFICATION_SERVICE_URL=http://notification-service:8004
      - FINANCIAL_SERVICE_URL=http://financial-service:8000
      - MEDICAL_SERVICE_URL=http://medical-service:8006
      - DEFAULT_CURRENCY=COP
      - MINIMUM_WAGE=1300000
      - HEALTH_CONTRIBUTION_RATE=0.04
      - PENSION_CONTRIBUTION_RATE=0.04
      - ARL_CONTRIBUTION_RATE=0.00522
      - INCOME_TAX_EXEMPT_AMOUNT=2392000
      - OVERTIME_MULTIPLIER=1.25
      - NIGHT_SHIFT_MULTIPLIER=1.35
      - HOLIDAY_MULTIPLIER=1.75
      - VACATION_DAYS_PER_YEAR=15
      - SEVERANCE_MULTIPLIER=1.0
      - THIRTEENTH_SALARY_ENABLED=true
      - FOURTEENTH_SALARY_ENABLED=true
    depends_on:
      - mysql-payroll
      - redis
    networks:
      - wl-school-network
    volumes:
      - ./microservices/payroll-service:/var/www
      - ./storage/logs/payroll:/var/www/storage/logs

  # Reports Service
  reports-service:
    build:
      context: ./microservices/reports-service
      dockerfile: Dockerfile
    ports:
      - "8008:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql-reports
      - DB_PORT=3306
      - DB_DATABASE=wl_school_reports
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE_CONNECTION=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - AUTH_SERVICE_URL=http://auth-service:8000
      - NOTIFICATION_SERVICE_URL=http://notification-service:8004
      - FINANCIAL_SERVICE_URL=http://financial-service:8000
      - MEDICAL_SERVICE_URL=http://medical-service:8006
      - PAYROLL_SERVICE_URL=http://payroll-service:9000
      - SPORTS_SERVICE_URL=http://sports-service:8000
      - CALENDAR_SERVICE_URL=http://calendar-service:8005
    depends_on:
      - mysql-reports
      - redis
    networks:
      - wl-school-network
    volumes:
      - ./microservices/reports-service:/var/www/html
      - ./storage/logs/reports:/var/www/html/storage/logs

  # Frontend PWA
  frontend-pwa:
    build:
      context: ./frontend-pwa
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=development
      - REACT_APP_AUTH_SERVICE_URL=http://localhost:8001
      - REACT_APP_FINANCIAL_SERVICE_URL=http://localhost:8002
      - REACT_APP_SPORTS_SERVICE_URL=http://localhost:8003
      - REACT_APP_NOTIFICATION_SERVICE_URL=http://localhost:8004
      - REACT_APP_CALENDAR_SERVICE_URL=http://localhost:8005
      - REACT_APP_MEDICAL_SERVICE_URL=http://localhost:8006
      - REACT_APP_PAYROLL_SERVICE_URL=http://localhost:8007
      - REACT_APP_REPORTS_SERVICE_URL=http://localhost:8008
    depends_on:
      - auth-service
      - financial-service
      - sports-service
      - notification-service
      - calendar-service
      - medical-service
      - payroll-service
      - reports-service
    networks:
      - wl-school-network
    volumes:
      - ./frontend-pwa:/app
      - /app/node_modules

  # Auth Database
  mysql-auth:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wl_school_auth
    ports:
      - "3307:3306"
    volumes:
      - mysql_auth_data:/var/lib/mysql
      - ./database/migrations/auth_service.sql:/docker-entrypoint-initdb.d/auth_service.sql
    networks:
      - wl-school-network

  # Financial Database
  mysql-financial:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wl_school_financial
    ports:
      - "3308:3306"
    volumes:
      - mysql_financial_data:/var/lib/mysql
      - ./database/migrations/financial_service.sql:/docker-entrypoint-initdb.d/financial_service.sql
    networks:
      - wl-school-network

  # Sports Database
  sports-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sports_service
      MYSQL_USER: sports_user
      MYSQL_PASSWORD: sports_password
    ports:
      - "3309:3306"
    volumes:
      - mysql_sports_data:/var/lib/mysql
    networks:
      - wl-school-network

  # Notifications Database
  mysql-notifications:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wl_school_notifications
    ports:
      - "3310:3306"
    volumes:
      - mysql_notifications_data:/var/lib/mysql
      - ./database/migrations/notification_service.sql:/docker-entrypoint-initdb.d/notification_service.sql
    networks:
      - wl-school-network

  # Calendar Database
  mysql-calendar:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: calendar_service
    ports:
      - "3311:3306"
    volumes:
      - mysql_calendar_data:/var/lib/mysql
    networks:
      - wl-school-network

  # Medical Database
  mysql-medical:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wl_school_medical
    ports:
      - "3312:3306"
    volumes:
      - mysql_medical_data:/var/lib/mysql
    networks:
      - wl-school-network

  # Payroll Database
  mysql-payroll:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wl_school_payroll
    ports:
      - "3313:3306"
    volumes:
      - mysql_payroll_data:/var/lib/mysql
      - ./database/migrations/payroll_service.sql:/docker-entrypoint-initdb.d/payroll_service.sql
    networks:
      - wl-school-network

  # Reports Database
  mysql-reports:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wl_school_reports
    ports:
      - "3314:3306"
    volumes:
      - mysql_reports_data:/var/lib/mysql
      - ./database/migrations/report_service.sql:/docker-entrypoint-initdb.d/report_service.sql
    networks:
      - wl-school-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wl-school-network
    command: redis-server --appendonly yes

  # Nginx Load Balancer
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./storage/logs/nginx:/var/log/nginx
    depends_on:
      - auth-service
      - financial-service
      - reports-service
      - frontend-pwa
    networks:
      - wl-school-network

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql-auth
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql-auth
      - mysql-financial
      - mysql-notifications
    networks:
      - wl-school-network

  # Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - wl-school-network

volumes:
  mysql_auth_data:
  mysql_financial_data:
  mysql_sports_data:
  mysql_notifications_data:
  mysql_calendar_data:
  mysql_medical_data:
  mysql_payroll_data:
  mysql_reports_data:
  redis_data:

networks:
  wl-school-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16