<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\Department;
use App\Models\Position;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            [
                'employee_number' => 'EMP-001',
                'first_name' => 'Carlos',
                'last_name' => 'Rodríguez',
                'email' => 'carlos.rodriguez@company.com',
                'phone' => '3001234567',
                'address' => 'Calle 100 #15-20, Bogotá',
                'identification_type' => 'CC',
                'identification_number' => '12345678',
                'birth_date' => '1975-03-15',
                'hire_date' => '2020-01-15',
                'base_salary' => 20000000.00,
                'employment_status' => 'active',
                'employment_type' => 'full_time',
                'gender' => 'M',
                'emergency_contact_name' => 'María Rodríguez',
                'emergency_contact_phone' => '3009876543',
                'bank_name' => 'Banco de Bogotá',
                'bank_account_type' => 'savings',
                'bank_account_number' => '123456789'
            ],
            [
                'employee_number' => 'EMP-002',
                'first_name' => 'Ana',
                'last_name' => 'García',
                'email' => 'ana.garcia@company.com',
                'phone' => '3002345678',
                'address' => 'Carrera 15 #80-45, Bogotá',
                'identification_type' => 'CC',
                'identification_number' => '23456789',
                'birth_date' => '1980-07-22',
                'hire_date' => '2021-03-10',
                'base_salary' => 10000000.00,
                'employment_status' => 'active',
                'employment_type' => 'full_time',
                'gender' => 'F',
                'emergency_contact_name' => 'Luis García',
                'emergency_contact_phone' => '3008765432',
                'bank_name' => 'Bancolombia',
                'bank_account_type' => 'checking',
                'bank_account_number' => '234567890'
            ],
            [
                'employee_number' => 'EMP-003',
                'first_name' => 'Miguel',
                'last_name' => 'López',
                'email' => 'miguel.lopez@company.com',
                'phone' => '3003456789',
                'address' => 'Calle 72 #11-35, Bogotá',
                'identification_type' => 'CC',
                'identification_number' => '34567890',
                'birth_date' => '1985-11-08',
                'hire_date' => '2022-01-20',
                'base_salary' => 5500000.00,
                'employment_status' => 'active',
                'employment_type' => 'full_time',
                'gender' => 'M',
                'emergency_contact_name' => 'Carmen López',
                'emergency_contact_phone' => '3007654321',
                'bank_name' => 'Banco Popular',
                'bank_account_type' => 'savings',
                'bank_account_number' => '345678901'
            ],
            [
                'employee_number' => 'EMP-004',
                'first_name' => 'Laura',
                'last_name' => 'Martínez',
                'email' => 'laura.martinez@company.com',
                'phone' => '3004567890',
                'address' => 'Carrera 7 #63-28, Bogotá',
                'identification_type' => 'CC',
                'identification_number' => '45678901',
                'birth_date' => '1990-04-12',
                'hire_date' => '2023-02-15',
                'base_salary' => 3250000.00,
                'employment_status' => 'active',
                'employment_type' => 'full_time',
                'gender' => 'F',
                'emergency_contact_name' => 'Pedro Martínez',
                'emergency_contact_phone' => '3006543210',
                'bank_name' => 'Davivienda',
                'bank_account_type' => 'savings',
                'bank_account_number' => '456789012'
            ],
            [
                'employee_number' => 'EMP-005',
                'first_name' => 'Roberto',
                'last_name' => 'Sánchez',
                'email' => 'roberto.sanchez@company.com',
                'phone' => '3005678901',
                'address' => 'Calle 45 #19-67, Bogotá',
                'identification_type' => 'CC',
                'identification_number' => '56789012',
                'birth_date' => '1988-09-25',
                'hire_date' => '2021-08-30',
                'base_salary' => 3500000.00,
                'employment_status' => 'active',
                'employment_type' => 'full_time',
                'gender' => 'M',
                'emergency_contact_name' => 'Elena Sánchez',
                'emergency_contact_phone' => '3005432109',
                'bank_name' => 'BBVA',
                'bank_account_type' => 'checking',
                'bank_account_number' => '567890123'
            ],
            [
                'employee_number' => 'EMP-006',
                'first_name' => 'Patricia',
                'last_name' => 'Herrera',
                'email' => 'patricia.herrera@company.com',
                'phone' => '3006789012',
                'address' => 'Carrera 30 #75-12, Bogotá',
                'identification_type' => 'CC',
                'identification_number' => '67890123',
                'birth_date' => '1983-12-03',
                'hire_date' => '2020-11-05',
                'base_salary' => 4250000.00,
                'employment_status' => 'active',
                'employment_type' => 'full_time',
                'gender' => 'F',
                'emergency_contact_name' => 'Jorge Herrera',
                'emergency_contact_phone' => '3004321098',
                'bank_name' => 'Banco de Occidente',
                'bank_account_type' => 'savings',
                'bank_account_number' => '678901234'
            ],
            [
                'employee_number' => 'EMP-007',
                'first_name' => 'Diego',
                'last_name' => 'Ramírez',
                'email' => 'diego.ramirez@company.com',
                'phone' => '3007890123',
                'address' => 'Calle 85 #20-40, Bogotá',
                'identification_type' => 'CC',
                'identification_number' => '78901234',
                'birth_date' => '1987-06-18',
                'hire_date' => '2022-05-12',
                'base_salary' => 3500000.00,
                'employment_status' => 'active',
                'employment_type' => 'full_time',
                'gender' => 'M',
                'emergency_contact_name' => 'Sofía Ramírez',
                'emergency_contact_phone' => '3003210987',
                'bank_name' => 'Colpatria',
                'bank_account_type' => 'savings',
                'bank_account_number' => '789012345'
            ],
            [
                'employee_number' => 'EMP-008',
                'first_name' => 'Claudia',
                'last_name' => 'Torres',
                'email' => 'claudia.torres@company.com',
                'phone' => '3008901234',
                'address' => 'Carrera 50 #68-25, Bogotá',
                'identification_type' => 'CC',
                'identification_number' => '89012345',
                'birth_date' => '1992-01-30',
                'hire_date' => '2023-07-08',
                'base_salary' => 4200000.00,
                'employment_status' => 'active',
                'employment_type' => 'full_time',
                'gender' => 'F',
                'emergency_contact_name' => 'Carlos Torres',
                'emergency_contact_phone' => '3002109876',
                'bank_name' => 'Banco Caja Social',
                'bank_account_type' => 'checking',
                'bank_account_number' => '890123456'
            ],
            [
                'employee_number' => 'EMP-009',
                'first_name' => 'Andrés',
                'last_name' => 'Morales',
                'email' => 'andres.morales@company.com',
                'phone' => '3009012345',
                'address' => 'Calle 92 #15-78, Bogotá',
                'identification_type' => 'CC',
                'identification_number' => '90123456',
                'birth_date' => '1986-08-14',
                'hire_date' => '2021-12-01',
                'base_salary' => 4800000.00,
                'employment_status' => 'active',
                'employment_type' => 'full_time',
                'gender' => 'M',
                'emergency_contact_name' => 'Lucía Morales',
                'emergency_contact_phone' => '3001098765',
                'bank_name' => 'Banco Agrario',
                'bank_account_type' => 'savings',
                'bank_account_number' => '901234567'
            ],
            [
                'employee_number' => 'EMP-010',
                'first_name' => 'Valentina',
                'last_name' => 'Castro',
                'email' => 'valentina.castro@company.com',
                'phone' => '3000123456',
                'address' => 'Carrera 25 #55-33, Bogotá',
                'identification_type' => 'CC',
                'identification_number' => '01234567',
                'birth_date' => '1994-05-27',
                'hire_date' => '2023-09-20',
                'base_salary' => 4200000.00,
                'employment_status' => 'active',
                'employment_type' => 'full_time',
                'gender' => 'F',
                'emergency_contact_name' => 'Ricardo Castro',
                'emergency_contact_phone' => '3000987654',
                'bank_name' => 'Banco AV Villas',
                'bank_account_type' => 'savings',
                'bank_account_number' => '012345678'
            ]
        ];

        foreach ($employees as $employee) {
            Employee::create($employee);
        }
    }
}