version: '3.8'

services:
  financial-service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: financial-service-dev
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      # Mount source code for hot reload
      - ./:/var/www
      # Exclude vendor and node_modules for performance
      - /var/www/vendor
      - /var/www/node_modules
      # PHP configuration for development
      - ./docker/php/dev.ini:/usr/local/etc/php/conf.d/dev.ini
    networks:
      - financial-network
    depends_on:
      - financial-db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=financial-db
      - DB_PORT=3306
      - DB_DATABASE=financial_service
      - DB_USERNAME=financial_user
      - DB_PASSWORD=financial_password
      - CACHE_DRIVER=array
      - SESSION_DRIVER=array
      - QUEUE_CONNECTION=sync

  financial-nginx:
    image: nginx:alpine
    container_name: financial-nginx-dev
    restart: unless-stopped
    ports:
      - "8003:80"
    volumes:
      # Mount source code for serving static files
      - ./:/var/www
      # Nginx configuration
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - financial-network
    depends_on:
      - financial-service

  financial-db:
    image: mysql:8.0
    container_name: financial-db-dev
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: financial_service
      MYSQL_USER: financial_user
      MYSQL_PASSWORD: financial_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - financial-db-data-dev:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - financial-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  financial-db-data-dev:
    driver: local

networks:
  financial-network:
    driver: bridge